module.exports = {
  deployment: require("./deployment"),
  runtime: {
    events: require("./runtime/events"),
    registry: require("./runtime/registry"),
    session: require("./runtime/session"),
    jobs: require("./runtime/jobs"),
    workflows: require("./runtime/workflows"),
    tasks: require("./runtime/tasks"),
    blockers: require("./runtime/blockers"),
    approvals: require("./runtime/approvals"),
    profiles: require("./runtime/profiles"),
    projects: require("./runtime/projects"),
    resolution: require("./runtime/resolution"),
    orchestrator: require("./runtime/orchestrator"),
  },
  dispatch: require("./dispatch"),
  execute: require("./execute"),
  continuation: require("./continuation"),
  actions: require("./actions"),
  ops: require("./ops"),
  mcp: require("./mcp"),
  remote: require("./remote"),
  routing: require("./routing"),
  instructions: require("./instructions"),
  envelope: require("./envelope"),
  playbooks: require("./playbooks"),
  stalled: require("./stalled"),
  taskRunner: require("./task-runner"),
  resolution: require("./resolution"),
}
