module.exports = {
  deployment: require("./deployment"),
  runtime: {
    agents: require("./runtime/agents"),
    events: require("./runtime/events"),
    registry: require("./runtime/registry"),
    session: require("./runtime/session"),
    jobs: require("./runtime/jobs"),
    profiles: require("./runtime/profiles"),
    projects: require("./runtime/projects"),
    orchestrator: require("./runtime/orchestrator"),
  },
  execute: require("./execute"),
  actions: require("./actions"),
  ops: require("./ops"),
  mcp: require("./mcp"),
  remote: require("./remote"),
  routing: require("./routing"),
  instructions: require("./instructions"),
  skills: require("./skills"),
  envelope: require("./envelope"),
  playbooks: require("./playbooks"),
  stalled: require("./stalled"),
}
